# Multistrand nucleic acid kinetic simulator
# Copyright (c) 2010-2017 California Institute of Technology. All rights reserved.
# The Multistrand Team (help@multistrand.org)

[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"
